// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sample.roo.flightapp.domain;

import java.io.Serializable;
import sample.roo.flightapp.domain.Address;

privileged aspect Address_Roo_Serializable {
    
    declare parents: Address implements Serializable;
    
    private static final long Address.serialVersionUID = 1L;
    
}
