// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sample.roo.flightapp.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sample.roo.flightapp.domain.FlightKey;

privileged aspect FlightKey_Roo_Configurable {
    
    declare @type: FlightKey: @Configurable;
    
}
