// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sample.roo.flightapp.service;

import java.io.Serializable;
import sample.roo.flightapp.service.FlightService;

privileged aspect FlightService_Roo_Serializable {
    
    declare parents: FlightService implements Serializable;
    
    private static final long FlightService.serialVersionUID = 1L;
    
}
